USE [master]
GO
/****** Object:  Database [PRJ_Assignment]    Script Date: 01/03/2023 15:34:15 ******/
CREATE DATABASE [PRJ_Assignment2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRJ_Assignment2', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRJ_Assignment2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRJ_Assignment2_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PRJ_Assignment2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PRJ_Assignment2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRJ_Assignment2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRJ_Assignment2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRJ_Assignment2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRJ_Assignment2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PRJ_Assignment2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRJ_Assignment2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET RECOVERY FULL 
GO
ALTER DATABASE [PRJ_Assignment2] SET  MULTI_USER 
GO
ALTER DATABASE [PRJ_Assignment2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRJ_Assignment2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRJ_Assignment2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRJ_Assignment2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRJ_Assignment2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRJ_Assignment2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PRJ_Assignment', N'ON'
GO
ALTER DATABASE [PRJ_Assignment2] SET QUERY_STORE = OFF
GO
USE [PRJ_Assignment2]
GO
/****** Object:  Table [dbo].[block]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[block](
	[block_ID] [int] IDENTITY(1,1) NOT NULL,
	[account_ID] int NOT NULL,
	[account_ID_block] int NOT NULL,
 CONSTRAINT [PK_block] PRIMARY KEY CLUSTERED 
(
	[block_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Gender]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gender](
	[gender_ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED 
(
	[gender_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[hobby]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hobby](
	[hobby_ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_hobby] PRIMARY KEY CLUSTERED 
(
	[hobby_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Interest_in_Hobby]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Interest_in_Hobby](
	[iih_ID] [int] IDENTITY(1,1) NOT NULL,
	[hobby_ID] int NOT NULL,
	[account_ID] int NOT NULL,
 CONSTRAINT [PK_Interest_in_Hobby] PRIMARY KEY CLUSTERED 
(
	[iih_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Interest_in_Relationship]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Interest_in_Relationship](
	[iir_ID] [int] IDENTITY(1,1) NOT NULL,
	[account_ID] int NOT NULL,
	[relation_ID] int NOT NULL,
 CONSTRAINT [PK_Interest_in_Relationship] PRIMARY KEY CLUSTERED 
(
	[iir_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[like]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[like](
	[like_ID] [int] IDENTITY(1,1) NOT NULL,
	[account_ID_send] int NOT NULL,
	[account_ID_received] int NOT NULL,
	[grade] [int] NOT NULL,
 CONSTRAINT [PK_like] PRIMARY KEY CLUSTERED 
(
	[like_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Location]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Location](
	[Location_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED 
(
	[Location_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Relationship]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Relationship](
	[relation_ID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Relationship] PRIMARY KEY CLUSTERED 
(
	[relation_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sex_Oriented]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sex_Oriented](
	[SO_ID] [int] IDENTITY(1,1) NOT NULL,
	[account_ID] int NOT NULL,
	[gender_ID] int NOT NULL,
 CONSTRAINT [PK_Sex_Oriented] PRIMARY KEY CLUSTERED 
(
	[SO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Account]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Account](
	[account_ID] [int] IDENTITY(1,1) NOT NULL,
	[first_name] [nvarchar](50) NOT NULL,
	[last_name] [nvarchar](50) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[password] [nvarchar](50) NOT NULL,
	[description] [nvarchar](200) NOT NULL,
	[gender_ID] int NOT NULL,
	[DOB] [date] NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Location_ID] int NOT NULL,
 CONSTRAINT [PK_User_Account] PRIMARY KEY CLUSTERED 
(
	[account_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Photo]    Script Date: 01/03/2023 15:34:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Photo](
	[photo_ID] [int] IDENTITY(1,1) NOT NULL,
	[account_ID] int NOT NULL,
	[link] [nvarchar](max) NOT NULL,
	[time_added] [timestamp] NOT NULL,
	[status] [nvarchar](200) NULL,
 CONSTRAINT [PK_User_Photo] PRIMARY KEY CLUSTERED 
(
	[photo_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[block]  WITH CHECK ADD  CONSTRAINT [fk_44] FOREIGN KEY([account_ID])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[block] CHECK CONSTRAINT [fk_44]
GO
ALTER TABLE [dbo].[block]  WITH CHECK ADD  CONSTRAINT [fk_45] FOREIGN KEY([account_ID_block])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[block] CHECK CONSTRAINT [fk_45]
GO
ALTER TABLE [dbo].[Interest_in_Hobby]  WITH CHECK ADD  CONSTRAINT [fk_15] FOREIGN KEY([hobby_ID])
REFERENCES [dbo].[hobby] ([hobby_ID])
GO
ALTER TABLE [dbo].[Interest_in_Hobby] CHECK CONSTRAINT [fk_15]
GO
ALTER TABLE [dbo].[Interest_in_Hobby]  WITH CHECK ADD  CONSTRAINT [fk_74] FOREIGN KEY([account_ID])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[Interest_in_Hobby] CHECK CONSTRAINT [fk_74]
GO
ALTER TABLE [dbo].[Interest_in_Relationship]  WITH CHECK ADD  CONSTRAINT [fk_10] FOREIGN KEY([relation_ID])
REFERENCES [dbo].[Relationship] ([relation_ID])
GO
ALTER TABLE [dbo].[Interest_in_Relationship] CHECK CONSTRAINT [fk_10]
GO
ALTER TABLE [dbo].[Interest_in_Relationship]  WITH CHECK ADD  CONSTRAINT [fk_7] FOREIGN KEY([account_ID])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[Interest_in_Relationship] CHECK CONSTRAINT [fk_7]
GO
ALTER TABLE [dbo].[like]  WITH CHECK ADD  CONSTRAINT [fk_42] FOREIGN KEY([account_ID_received])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[like] CHECK CONSTRAINT [fk_42]
GO
ALTER TABLE [dbo].[like]  WITH CHECK ADD  CONSTRAINT [fk_43] FOREIGN KEY([account_ID_send])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[like] CHECK CONSTRAINT [fk_43]
GO
ALTER TABLE [dbo].[Sex_Oriented]  WITH CHECK ADD  CONSTRAINT [fk_3] FOREIGN KEY([gender_ID])
REFERENCES [dbo].[Gender] ([gender_ID])
GO
ALTER TABLE [dbo].[Sex_Oriented] CHECK CONSTRAINT [fk_3]
GO
ALTER TABLE [dbo].[Sex_Oriented]  WITH CHECK ADD  CONSTRAINT [fk_4] FOREIGN KEY([account_ID])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[Sex_Oriented] CHECK CONSTRAINT [fk_4]
GO
ALTER TABLE [dbo].[User_Account]  WITH CHECK ADD  CONSTRAINT [fk_2] FOREIGN KEY([gender_ID])
REFERENCES [dbo].[Gender] ([gender_ID])
GO
ALTER TABLE [dbo].[User_Account] CHECK CONSTRAINT [fk_2]
GO
ALTER TABLE [dbo].[User_Account]  WITH CHECK ADD  CONSTRAINT [fk_ten1234] FOREIGN KEY([Location_ID])
REFERENCES [dbo].[Location] ([Location_ID])
GO
ALTER TABLE [dbo].[User_Account] CHECK CONSTRAINT [fk_ten1234]
GO
ALTER TABLE [dbo].[User_Photo]  WITH CHECK ADD  CONSTRAINT [fk_6] FOREIGN KEY([account_ID])
REFERENCES [dbo].[User_Account] ([account_ID])
GO
ALTER TABLE [dbo].[User_Photo] CHECK CONSTRAINT [fk_6]
GO
USE [master]
GO
ALTER DATABASE [PRJ_Assignment2] SET  READ_WRITE 
GO
